###=====================###
### CONFIGURATION START ###
###=====================###

outputDirectory <- '/path/to/output_directory/';

# This file is generated by 00_contig_stat.ssh
contigLengthsFile <- file.path(outputDirectory, 'contigLengths.txt')

# Pop1 will be the main population whose data will be analysed
# When you want to generate charts for two populations, remember to run this script twice and swap pop1 and pop2 variables with each other
pop1Directory <- file.path(outputDirectory, 'Gifu-MG20')
pop1Name <- 'Gifu x MG20'

# Next iteration:
# pop1Directory <- file.path(outputDirectory, 'Gifu-Burttii')
# pop1Name <- 'Gifu x Burttii'

# Pop2 will be only for comparative purposes
# When you want to generate charts for two populations, remember to run this script twice and swap pop1 and pop2 variables with each other
pop2Directory <- file.path(outputDirectory, 'Gifu-Burttii')
pop2Name <- 'Gifu x Burttii'

# Next iteration
# pop2Directory <- file.path(outputDirectory, 'Gifu-MG20')
# pop2Name <- 'Gifu x MG20'

###=====================###
### CONFIGURATION END   ###
###=====================###


library(ggplot2)
library(gplots)
library(reshape2)
library(ape)
library(RColorBrewer)

# Data: contig consensus matrix
data <- read.csv(file.path(pop1Directory,'contigConsensusMatrix.txt'),
                 header=T,
                 sep=",",
                 stringsAsFactors=F)

# Data2: contig consensus, which contains confidence scores that need to be trimmed out
contigConsensusParser <- function(contigConsensusFile) {
  data2 <- read.csv(contigConsensusFile,
                    header=T,
                    sep="\t",
                    stringsAsFactors=T)
  data2.subset <- data2[, 1:((ncol(data2)-3)/2+1)]
  data2.subset.parsed <- lapply(data2.subset, function(x) {
    gsub('A', 0, x)
  })
  data2.subset.parsed <- lapply(data2.subset.parsed, function(x) {
    gsub('B', 1, x)
  })
  data2.subset.parsed <- lapply(data2.subset.parsed, function(x) {
    gsub('X', 0.5, x)
  })
  data2.subset.parsed <- lapply(data2.subset.parsed, function(x) {
    gsub('-', NA, x)
  })
  data2.subset.parsed <- data.frame(data2.subset.parsed)
  data2.subset.parsed.dataCol <- lapply(data2.subset.parsed[, 2:ncol(data2.subset.parsed)], function(x) {
    as.numeric(as.character(x))
  })
  data2.final <- cbind(data2.subset.parsed[,1], data.frame(data2.subset.parsed.dataCol))
  rownames(data2.final) <- data2.subset.parsed[,1]
  data2.final <- data2.final[,2:ncol(data2.final)]
  data2.averageConfidence <- cbind(data.frame(data2[,1]), data.frame(data2[, (ncol(data2)-1)]))
  names(data2.averageConfidence) <- c('Contig','AverageConfidence')
  
  dataFrames <- vector("list", length(2))
  dataFrames[[1]] <- data2.final
  dataFrames[[2]] <- data2.averageConfidence
  dataFrames
}

thisContigConsensus <- contigConsensusParser(file.path(pop1Directory,'contigConsensus.csv'))
thatContigConsensus <- contigConsensusParser(file.path(pop2Directory,'contigConsensus.csv'))

contigLengths <- read.csv(contigLengthsFile,
                          header=F,
                          sep="\t",
                          stringsAsFactors=F)
names(contigLengths) <- c('Contig', 'Length')


# Melt data
data.melted <- reshape(data,
                       varying = c("SimilarityScore", "IdentityScore"),
                       v.names = "Score",
                       timevar = "ScoreType",
                       times = c("SimilarityScore", "IdentityScore"),
                       direction = "long")

# HISTOGRAMS
# Visualise distribution of similarity scores
p.histogram <- ggplot(
  data.melted,
  aes(x = Score)
) + geom_histogram(
  aes(
    y = ..density..
  ),
  stat = "bin",
  binwidth = 0.02,
  colour = "#333333",
  fill = "#ffffff"
) + geom_density(
  alpha = 0.2,
  fill = "steelblue"
) + theme_bw() + facet_grid(. ~ ScoreType) + ggtitle('Histogram and density plot of contig consensus scores')
pdf(file.path(pop1Directory,paste(Sys.Date(), "score_histogram.pdf", sep='-')),
    width = 12,
    height = 6)
print(p.histogram)
dev.off()
png(file.path(pop1Directory,paste(Sys.Date(), "score_histogram.png", sep='-')),
    width = 12,
    height = 6,
    res = 300,
    units = "in")
print(p.histogram)
dev.off()


# HEATMAP
# Plot heatmap
data.melted.filtered <- subset(data.melted, Score > 0.7)
p.heatmap <- ggplot(
  data.melted.filtered,
  aes(
    x = Contig1,
    y = Contig2
  )
) + geom_tile(
  aes(fill = Score)
) + theme_bw() + theme(
  axis.ticks = element_blank(),
  axis.text = element_blank()
) + facet_grid(. ~ ScoreType) + ggtitle('Scores of 2D matrix for pairwise contig consensus omparisons')
pdf(file.path(pop1Directory,"pairwise_contig_scores.pdf"),
    width = 24,
    height = 12)
print(p.heatmap)
dev.off()
png(file.path(pop1Directory,paste(Sys.Date(), "pairwise_contig_scores.png", sep='-')),
    width = 24,
    height = 12,
    res = 300,
    units = "in")
print(p.heatmap)
dev.off()


# Draw heatmap
thishc.rows <- hclust(dist(thisContigConsensus[[1]]))
thishc.cols <- hclust(t(dist(thisContigConsensus[[1]])))
thisContigConsensus.matrix <- as.matrix(thisContigConsensus[[1]])
heatmap.palette <- colorRampPalette(c('#334D5C', '#EFC94C', '#DF5A49'))(n = 10)
pdf(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig_gplot.pdf", sep='-')),
    width = 24,
    height = 12)
heatmap.2(thisContigConsensus.matrix,
          Colv = NA,
          labRow = NA,
          labCol = NA,
          trace = 'none',
          dendrogram = 'row',
          col = heatmap.palette)
dev.off()
png(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig_gplot.png", sep='-')),
    width = 24,
    height = 12,
    res = 300,
    units = "in")
heatmap.2(thisContigConsensus.matrix,
          Colv = NA,
          labRow = NA,
          labCol = NA,
          trace = 'none',
          dendrogram = 'row',
          col = heatmap.palette)
dev.off()


# Export newick file
write.tree(phy = as.phylo(thishc.rows),
           file=file.path(pop1Directory, paste(Sys.Date(), 'contig-tree.newick', sep="-")))

clusteredContig <- data.frame(thishc.rows$labels[c(thishc.rows$order)])
names(clusteredContig) <- c('Contig')

clusteredContig$id <- 1:nrow(clusteredContig)

orderedContig <- merge(clusteredContig, thisContigConsensus[[1]], by.x='Contig', by.y='row.names')
orderedContig <- merge(data.frame(Contig = contigLengths$Contig), orderedContig, by.x="Contig", by.y="Contig", all.x=T)
orderedContig <- orderedContig[order(orderedContig$id), ]
orderedContig$Dataset <- pop1Name

# Draw heatmap using ggplot <3
# Reorder levels using thishc.rows
contigPresent <- thishc.rows$labels[c(thishc.rows$order)]
contigAbsent <- setdiff(contigLengths$Contig, contigPresent)
orderedContig$Contig <- factor(orderedContig$Contig, levels = c(contigPresent, contigAbsent))
orderedContig.melted <- melt(orderedContig,
                             id = c('Contig', 'id', 'Dataset'),
                             variable.name = 'RIL',
                             value.name = 'Genotype')
p.clusteredHeatmap <- ggplot(
  subset(orderedContig.melted, Dataset == pop1Name & !(Contig %in% contigAbsent)),
  aes(
    x = RIL,
    y = Contig,
    fill = factor(Genotype)
  )
) + geom_tile() + scale_fill_manual(
  values = c('#334D5C', '#EFC94C', '#DF5A49', '#333333')
) + theme_bw() + theme(
  axis.text = element_blank(),
  axis.ticks = element_blank()
)
png(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig_ggplot.png", sep='-')),
    width = 24,
    height = 12,
    res = 300,
    units = "in")
p.clusteredHeatmap
dev.off()
pdf(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig_ggplot.pdf", sep='-')),
    width = 24,
    height = 12)
p.clusteredHeatmap
dev.off()


# Draw heatmap using ggplot <3
# But this time using joined data from alternative dataset, too!
altContigConsensus <- tibble::rownames_to_column(thatContigConsensus[[1]], "Contig")
altContigConsensus$Dataset <- pop2Name
altContigConsensus$id <- NA
altContigConsensus.melted <- melt(altContigConsensus,
                                   id = c('Contig', 'id', 'Dataset'),
                                   variable.name = 'RIL',
                                   value.name = 'Genotype')
allContigConsensus.melted <- rbind(subset(orderedContig.melted, !Contig %in% contigAbsent), altContigConsensus.melted)
allContigConsensus.melted$Dataset <- factor(allContigConsensus.melted$Dataset, levels = c(pop1Name, pop2Name))
p.clusteredHeatmapAll <- ggplot(
  allContigConsensus.melted,
  aes(
    x = RIL,
    y = Contig,
    fill = factor(Genotype)
  )
) + geom_tile() + scale_fill_manual(
  values = c('#334D5C', '#EFC94C', '#DF5A49', '#333333')
) + theme_bw() + theme(
  axis.text = element_blank(),
  axis.ticks = element_blank()
) + facet_grid(. ~ Dataset, scales="free_x")
png(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig", pop1Name, pop2Name, "ggplot.png", sep='-')),
    width = 24,
    height = 12,
    res = 300,
    units = "in")
p.clusteredHeatmapAll
dev.off()
pdf(file.path(pop1Directory,paste(Sys.Date(), "clustered-contig", pop1Name, pop2Name, "ggplot.pdf", sep='-')),
    width = 24,
    height = 12)
p.clusteredHeatmapAll
dev.off()



# Export numerical matrix, join contig lengths
contigOut <- merge(orderedContig, contigLengths, by.x='Contig', by.y='Contig')
contigOut <- merge(contigOut, thisContigConsensus[[2]], by.x='Contig', by.y='Contig')
contigOut <- contigOut[order(contigOut$id),]
contigOut$id <- NULL
write.table(contigOut,
            file=file.path(pop1Directory,paste(Sys.Date(), 'ordered-contig-matrix.csv', sep='-')),
            sep="\t",
            quote=F,
            row.names=F)

# Data3: all genotype calls
# Get the maximum column number, discard the first 12 rows (settings for MSTmap), use 13th row as colnames
Ncol <- max(unlist(lapply(strsplit(readLines(file.path(pop1Directory,'refiltered.merged.012.transposed')), "\t"), length)))
data3 <- read.csv(file.path(pop1Directory,'refiltered.merged.012.transposed'),
                  header=F,
                  sep="\t",
                  stringsAsFactors=T,
                  colClasses="character",
                  col.names=paste0("V", 1:Ncol))
data3 <- tail(data3, -12)
colnames(data3) <- data3[1,]
data3 <- data3[-1,]

# Parse contig
contigPosData <- strsplit(as.character(data3$locus_name), "[.]")
contigPosDF <- do.call(rbind, contigPosData)
colnames(contigPosDF) <- c('Contig', 'Position')
data3.parsed <- cbind(contigPosDF, data3)
data3.parsed$Position <- as.numeric(as.character(data3.parsed$Position))

orderedContigDF <- data.frame(orderedContig$Contig)
colnames(orderedContigDF) <- c('Contig')
orderedContigDF$id <- 1:nrow(orderedContigDF)

# Export ordered genotype calls
contigCallsOut <- merge(orderedContigDF, data3.parsed, by.x="Contig", by.y="Contig")
contigCallsOut <- contigCallsOut[order(contigCallsOut$id, contigCallsOut$Position), ]
contigCallsOut$id <- NULL
write.table(contigCallsOut,
            file=file.path(pop1Directory,paste(Sys.Date(), 'ordered-contig-calls.csv', sep='-')),
            sep="\t",
            quote=F,
            row.names=F)

# Get list of unlisted contigs
allContigs <- data.frame(Contig = contigLengths$Contig)
outContigs <- data.frame(Contig = orderedContig$Contig)
missingContigs <- subset(allContigs, !(Contig %in% outContigs$Contig))
missingContigOut <- merge(contigLengths, missingContigs, by.x="Contig", by.y="Contig")
rownames(missingContigOut) <- missingContigOut$Contig
missingContigOut$Contig <- NULL
missingContigOut["Total",] <- colSums(missingContigOut)
missingContigOut <- tibble::rownames_to_column(missingContigOut, var = "Contig")
write.table(missingContigOut,
            file=file.path(pop1Directory,paste(Sys.Date(), 'missing-contigs.csv', sep='-')),
            sep="\t",
            quote=F,
            row.names=F)

# Get list of listed contigs
presentContigs <- subset(allContigs, Contig %in% outContigs$Contig)
presentContigOut <- merge(contigLengths, presentContigs, by.x="Contig", by.y="Contig")
rownames(presentContigOut) <- presentContigOut$Contig
presentContigOut$Contig <- NULL
presentContigOut["Total",] <- colSums(presentContigOut)
presentContigOut <- tibble::rownames_to_column(presentContigOut, var = "Contig")
write.table(presentContigOut,
            file=file.path(pop1Directory,paste(Sys.Date(), 'present-contigs.csv', sep='-')),
            sep="\t",
            quote=F,
            row.names=F)

